app_version: '28.1'
capabilities: []
categories:
- financial
date_added: '2025-08-01'
description: Run your personal node powered by Bitcoin Knots.
home: https://bitcoinknots.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/bitcoind/icons/icon.png
keywords:
- bitcoin
- cryptocurrency
- blockchain
lib_version: 2.1.43
lib_version_hash: 4dfe5c38b4319c62c2f1ca4db1f35dfa3bfc6cfe2836f14c7afff11fd85e13be
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: bitcoind-knots
run_as_context:
- description: Bitcoin Node runs as non-root user.
  gid: 981
  group_name: bitcoind
  uid: 993
  user_name: bitcoind
screenshots: []
sources:
- https://bitcoinknots.org
- https://github.com/Retropex/docker-bitcoind-truenas.git
title: Bitcoin Knots
train: community
version: 1.0.0
