app_version: '28.1'
capabilities: []
categories:
- financial
date_added: '2025-08-01'
description: Run your personal node powered by Bitcoin Knots.
home: https://bitcoinknots.org
host_mounts: []
icon: https://media.sys.truenas.net/apps/bitcoind/icons/icon.png
keywords:
- bitcoin
- cryptocurrency
- blockchain
lib_version: 2.1.35
lib_version_hash: 1bd4e0058fbd4d7c207df2cae606580065e8e6dba3e232f41bc1b006848b05d2
maintainers:
- email: leo@haf.ovh
  name: Léo
  url: haf.ovh
name: bitcoind-knots
run_as_context:
- description: Bitcoin Node runs as non-root user.
  gid: 981
  group_name: bitcoind
  uid: 993
  user_name: bitcoind
screenshots: []
sources:
- https://bitcoinknots.org
- https://github.com/Retropex/docker-bitcoind-truenas.git
title: Bitcoin Knots
train: community
version: 1.0.0
